# =============================================================================
# Portainer Stack - 3CX Translator (Gemini via Vertex AI)
# =============================================================================
#
# Deploy via Portainer:
# 1. Stacks → Add stack
# 2. Paste this content or upload file
# 3. Add environment variables below
# 4. Deploy
#
# Required environment variables in Portainer:
#   - GOOGLE_CLOUD_PROJECT: Your GCP project ID
#   - GOOGLE_CREDENTIALS_PATH: Path to service account JSON on host
#
# =============================================================================

version: '3.8'

services:
  gemini-translator:
    image: ghcr.io/luminalpark/gemini-translator:latest
    container_name: 3cx-translator

    ports:
      - "8001:8001"

    volumes:
      # Mount credentials file for Vertex AI authentication
      - ${GOOGLE_CREDENTIALS_PATH:-./credentials.json}:/app/credentials.json:ro
      - translator_logs:/app/logs

    environment:
      # ===== REQUIRED: Vertex AI Configuration =====
      - GOOGLE_CLOUD_PROJECT=${GOOGLE_CLOUD_PROJECT}
      - GOOGLE_CLOUD_LOCATION=${GOOGLE_CLOUD_LOCATION:-europe-west4}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json

      # ===== SERVER =====
      - SERVER_PORT=8001
      - SERVER_HOST=0.0.0.0
      - LOG_LEVEL=${LOG_LEVEL:-info}

      # ===== GEMINI MODEL =====
      # GA model for Live API with native audio (Dec 2025)
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-live-2.5-flash-native-audio}

      # ===== VOICE =====
      # Options: Aoede, Charon, Fenrir, Kore, Puck
      - GEMINI_VOICE=${GEMINI_VOICE:-Kore}

      # ===== TRANSLATION =====
      # Source: auto, de, es, en, fr, it
      - DEFAULT_SOURCE_LANG=${DEFAULT_SOURCE_LANG:-auto}
      # Target: de, es, en, fr, it
      - DEFAULT_TARGET_LANG=${DEFAULT_TARGET_LANG:-it}

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  translator_logs:
    driver: local
