# =============================================================================
# Portainer Stack - 3CX Translator (Gemini)
# =============================================================================
#
# Deploy via Portainer:
# 1. Stacks → Add stack
# 2. Paste this content or upload file
# 3. Add environment variables below
# 4. Deploy
#
# =============================================================================

version: '3.8'

services:
  gemini-translator:
    image: ghcr.io/YOUR_GITHUB_USERNAME/gemini-translator:latest
    container_name: 3cx-translator

    ports:
      - "8001:8001"

    volumes:
      - translator_logs:/app/logs

    environment:
      # ===== REQUIRED =====
      - GEMINI_API_KEY=${GEMINI_API_KEY}

      # ===== SERVER =====
      - SERVER_PORT=8001
      - SERVER_HOST=0.0.0.0
      - LOG_LEVEL=${LOG_LEVEL:-info}

      # ===== GEMINI MODEL =====
      # Options: gemini-2.0-flash-exp, gemini-2.5-flash-native-audio-preview-12-2025
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.0-flash-exp}

      # ===== VOICE =====
      # Options: Aoede, Charon, Fenrir, Kore, Puck
      - GEMINI_VOICE=${GEMINI_VOICE:-Kore}

      # ===== TRANSLATION =====
      # Source: auto, de, es, en, fr, it
      - DEFAULT_SOURCE_LANG=${DEFAULT_SOURCE_LANG:-auto}
      # Target: de, es, en, fr, it
      - DEFAULT_TARGET_LANG=${DEFAULT_TARGET_LANG:-it}

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  translator_logs:
    driver: local
